services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - pg-network
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - 5432:5432
    networks:
      - pg-network
    volumes:
      - ./volumes/ny_taxi_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", root"]
      interval: 5s
      retries: 5
    restart: always
  # ingest-data:
  #   container_name: ingest-data
  #   image: taxi_ingest_data:v001
  #   networks:
  #     - pg-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./scripts:/app
  #   command:
  #     - "--user=root"
  #     - "--password=root"
  #     - "--host=postgres"
  #     - "--port=5432"
  #     - "--db=ny_taxi"
  #     - "--table_name=taxi_trips"
  #     - "--parquet_file_url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"
  #     - "--parquet_file_name=./data/yellow_tripdata_2021-01.parquet"
  #     - "--load_batch_size=300000"

# volumes:
#   ny_taxi_pg_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./volumes/ny_taxi_pg_data
#   pgadmin-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./volumes/pgadmin-data
#   ingest-scripts:

networks:
  pg-network:
    driver: bridge
    name: pg-network
