services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - pg-network
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - 5432:5432
    networks:
      - pg-network
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", root"]
      interval: 5s
      retries: 5
    restart: always

# The volumes section is used to persist the data in the database
#  and allows the data to be shared between the containers.
volumes:
  postgres-db-volume:

networks:
  pg-network:
    driver: bridge
# *****************************************
# ********** Equivalents in bash **********
# *****************************************
# - Note: everything below is equivalent to the docker-compose.yaml file above

# |--------------------------------------------------------------------------
# ****** 1. Creating a volume ******
# docker volume create postgres-db-volume
# |--------------------------------------------------------------------------

# |--------------------------------------------------------------------------
# ****** 2. Creating a network (in order to connect the containers) ******
# - Note: The database will be avaialable under "postgres" hostname
#   and the pgadmin will be available under "pgadmin" hostname
#   in the network. This means that pgadmin will need to connect to host "postgres" on port 5432
# docker network create pg-network
# |--------------------------------------------------------------------------

# |--------------------------------------------------------------------------
# ************* postgres *************
# docker run -it \
#   --name postgres \
#   -e POSTGRES_USER="root" \
#   -e POSTGRES_PASSWORD="root" \
#   -e POSTGRES_DB="ny_taxi" \
#   -v $(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
#   -p 5432:5432 \
#   --network pg-network \
#   postgres:13
# |--------------------------------------------------------------------------

# |--------------------------------------------------------------------------
# ************* pgadmin *************
# docker run -it \
#   --name pgadmin \
#   -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
#   -e PGADMIN_DEFAULT_PASSWORD="admin" \
#   -p 8080:80 \
#   --network pg-network \
#   dpage/pgadmin4
# |--------------------------------------------------------------------------
